version: '3.8'

services:
  frontend:
    build:
      context: ./m347-ref-card-03-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./m347-ref-card-03-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
