version: '3.8'

services:
  frontend:
    build:
      context: ./m347-ref-card-03-fe
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./m347-ref-card-03-be
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge