
FROM node:18.17.0 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:18.17.0-alpine

WORKDIR /app
COPY --from=builder /app ./

EXPOSE 3000

ENV NEXT_PUBLIC_API_URL=http://backend:8080

CMD ["npm", "run", "start"]
